site_name: OpenAI Guardrails TypeScript
site_url: https://openai.github.io/openai-guardrails-js/
site_dir: site
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.sections
    - navigation.expand
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.svg
  favicon: assets/images/favicon-platform.svg

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
nav:
  - Intro: index.md
  - Examples: examples.md
  - Documentation:
    - Quickstart: quickstart.md
    - "Streaming vs Blocking": streaming_output.md
    - Tripwires: tripwires.md
    - Checks:
        - Contains PII: ref/checks/pii.md
        - Custom Prompt Check: ref/checks/custom_prompt_check.md
        - Hallucination Detection: ref/checks/hallucination_detection.md
        - Jailbreak Detection: ref/checks/jailbreak.md
        - Moderation: ref/checks/moderation.md
        - NSFW: ref/checks/nsfw.md
        - Off Topic Prompts: ref/checks/off_topic_prompts.md
        - Prompt Injection Detection: ref/checks/prompt_injection_detection.md
        - URL Filter: ref/checks/urls.md
    - Evaluation Tool: evals.md
  - API Reference:
    - Types: ref/types-typescript.md
    - Exceptions: ref/exceptions-typescript.md

extra:
  generator: false
  language: en

validation:
  omitted_files: warn
  absolute_links: ignore
  unrecognized_links: warn
  anchors: warn

extra_css:
  - stylesheets/extra.css

watch:
  - "src"
