[project]
name = "openai-guardrails-js-docs"
version = "0.1.4"
description = "Documentation for OpenAI Guardrails JS"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "pymdown-extensions>=10.0.0",
    "mkdocs-i18n>=0.4.3"
]